[package]
name = "habitat-launcher-client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
bincode = "*"
env_logger = "*"
habitat_core = { path = "../core" }
habitat-launcher-protocol = { path = "../launcher-protocol" }
habitat_common = { path = "../common" }
ipc-channel = { version = "*" }
libc = "*"
log = "*"
prost = "*"
serde = "*"
thiserror = "*"
