[package]
name = "test-probe"
version = "0.1.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
actix-rt = "*"
actix-web = { version = "4.0.0-beta.8", default-features = false, features = [ "rustls" ] }
clap = { git = "https://github.com/habitat-sh/clap.git", branch = "v2-master", features = [ "suggestions", "color", "unstable" ] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
toml = "*"
