[package]
name = "habitat_sup"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "./build.rs"
workspace = "../../"

[lib]
name = "habitat_sup"

[[bin]]
name = "hab-sup"
path = "src/main.rs"
doc = false

[dependencies]
bytes = "*"
actix-web = { version = "4.0.0-beta.8", default-features = false, features = [ "rustls" ] }
actix-rt = "*"
byteorder = "*"
clap = { git = "https://github.com/habitat-sh/clap.git", branch = "v2-master", features = [ "suggestions", "color", "unstable" ] }
configopt = { git = "https://github.com/habitat-sh/configopt.git" }
cpu-time = "*"
derivative = "*"
fs2 = "*"
futures = "*"
glob = "*"
hab = { path = "../hab" }
habitat_butterfly = { path = "../butterfly", default-features = false }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat_api_client = { path = "../builder-api-client" }
habitat_http_client = { path = "../http-client" }
habitat-launcher-client = { path = "../launcher-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
log4rs = "*"
notify = "*"
num_cpus = "*"
parking_lot = "*"
pin-project = "*"
prometheus = "*"
prost = { version = "*", features = ["prost-derive"] }
prost-types = "*"
rand = "*"
rants = { git = "https://github.com/habitat-sh/rants.git", features = ["native-tls"] }
regex = "*"
rustls = "*"
serde = { version = "*", features = ["rc"] }
serde_derive = "*"
serde_json = { version = "*", features = [ "preserve_order" ] }
serde_yaml = "*"
serde-transcode = "*"
state = "*"
structopt = { git = "https://github.com/habitat-sh/structopt.git" }
tempfile = "*"
termcolor = "*"
thiserror = "*"
anyhow = { version = "*", features = ["backtrace"] }
toml = { version = "*", features = ["preserve_order"]}
tokio = { version = "*", features = ["full"] }
tokio-rustls = "*"
tokio-util = { version = "*", features = ["full"] }
url = "*"
valico = "*"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
habitat-launcher-protocol = { path = "../launcher-protocol" }
mio = { version = "*", features = ["os-ext"] }
uuid = { version = "*", features = ["v4"] }
winapi = { version = "*", features = ["namedpipeapi", "tlhelp32"] }

[dev-dependencies]
habitat_core = { path = "../core" }
hyper = "*"
reqwest = { version = "*", features = ["json"] }

[target.'cfg(not(windows))'.dev-dependencies]
nix = "*"

[build-dependencies]
prost-build = "*"

[features]
default = []
apidocs = []
ignore_integration_tests = []
lock_as_rwlock = ["habitat_common/lock_as_rwlock"]
lock_as_mutex = ["habitat_common/lock_as_mutex"]
